<a href="https://colab.research.google.com/github/Amankumarpandey3/Generative-AI/blob/main/Text_Representation_Word_Embedding_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bag of Words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch Aman",
                           "dswithbappy watch Aman",
                           "people write comment",
                           "Aman write comment"],"output":[1,1,0,0]})

In [3]:
df

text  output
0       people watch Aman       1
1  dswithbappy watch Aman       1
2    people write comment       0
3      Aman write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [6]:
#Vocabulary
print(cv.vocabulary_)

{'people': 3, 'watch': 4, 'aman': 0, 'dswithbappy': 2, 'write': 5, 'comment': 1}


In [8]:
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12 stored elements and shape (4, 6)>

In [7]:
bow.toarray()

array([[1, 0, 0, 1, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 1, 0, 0, 0, 1]])

In [9]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())


[[1 0 0 1 1 0]]
[[1 0 1 0 1 0]]
[[0 1 0 1 0 1]]


In [10]:
# new
cv.transform(['Aman watch dswithAman']).toarray()

array([[1, 0, 0, 0, 1, 0]])

In [11]:
X = bow.toarray()
y = df['output']

N-grams

In [12]:
df = pd.DataFrame({"text":["people watch Aman",
                           "dswithbappy watch Aman",
                           "people write comment",
                           "Aman write comment"],"output":[1,1,0,0]})

In [13]:
df

text  output
0       people watch Aman       1
1  dswithbappy watch Aman       1
2    people write comment       0
3      Aman write comment       0

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

In [15]:
arr = tfid.fit_transform(df['text']).toarray()

In [16]:
arr

array([[0.49681612, 0.        , 0.        , 0.61366674, 0.61366674,
        0.        ],
       [0.44809973, 0.        , 0.70203482, 0.        , 0.55349232,
        0.        ],
       [0.        , 0.57735027, 0.        , 0.57735027, 0.        ,
        0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.        ,
        0.61366674]])

In [17]:
print(tfid.idf_)

[1.22314355 1.51082562 1.91629073 1.51082562 1.51082562 1.51082562]
